 
baseURL: "https://pdimens.github.io/"
languageCode: "en-us"
title: "Pavel Dimens"
theme: hugo-profile
canonifyURLs: true
publishDir: "docs"
Paginate: 20
disqusShortname: #gurusabarish
googleAnalytics: #G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: tutorials
      name: Tutorials
      title: Helpful posts
      url: /posts
      weight: 1
#    - identifier: gallery
#      name: Gallery
#      title: Graphic Gallery
#      url: /gallery/technical
#      weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Pavel Dimens"
  description: Marine Population Genomics and Evolution
  # staticPath: ""  # The path to serve the static files from
  favicon: "images/hero.svg"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  theme:
    disableThemeToggle: false
    defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  #  navbar:100
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable



  # Hero
  hero:
    enable: true
    intro: "Hi, I'm"
    title: "Pavel Dimens."
    subtitle: "I study population ecology in marine systems using genomics"
    content: "My focus has typically been highly migratory marine fishes, but not always! I also emphasize lowering the barrier of entry to learn new tools/methods and try to develop user-friendly tools within my discipline."
    image: /images/hero.jpg
    button:
      enable: true
      name: "CV"
      url: "CV_Dimens.pdf"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://www.github.com/pdimens
        - icon: fab fa-mastodon
          url: https://fediscience.org/@pvdimens
      customIcons:
        - icon: images/popgen.svg
          url: "https://biojulia.net/PopGen.jl/"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/image2.jpg"
    content: |-
      I'm an marine fish ecologist masquerading as a bioinformatician/geneticist. I studied a coastal shark species for my Masters degree and  *all* the tuna species for my PhD.
      
      Over the years I developed an affinity for the technical and analytical parts of research, along with a [some would argue] pedantic attention to detail in presentation aesthetics. As a result, I design 99% of all of my graphics, templates, gifs from scratch.

      I also adhere to modern approaches to research reproducibility, so I lean heavily on integrating GitHub, Jupyter Notebooks, conda environments, and Snakemake workflows for ~100% transparency.

      Besides work, I enjoy cooking, hiking, swimming, rock climbing, scuba diving, relaxing and doing nothing, coding in Julia, carpentry, and the occasional platformer or RPG video game.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Julia"
        - "R"
        - "Python"
        - "Bash"
        - "Jupyter"
        - "Snakemake"
        - "SLURM"
        - "ddRAD-seq"
        - "Haplotag linked-reads"
        - "Oxford Nanopore"
        - "GitHub Actions"

  # Experience
  experience:
    enable: true
    items:
      - job: "Postdoctoral Fellow"
        company: "Cornell University"
        companyUrl: "https://www.therkildsenlab.org/"
        date: "Sept 2023 - present"
        info:
          enable: false
        featuredLink:
          enable: false
        content: |
          Using haplotag linked-read technology, I'm investigating the population-level climate change induce range shifts
          in the American Shad (Alosa sapidissima).
    
      - job: "STEM Techincal Developer"
        company: "eCornell"
        companyUrl: "https://ecornell.cornell.edu/"
        date: "Aug 2021 - Sept 2023"
        info:
          enable: false
        featuredLink:
          enable: false
        content: |
          I am currently working as a Technical Developer for STEM (Science Technology Engineering Math) courses. The courses include:
          
          - Big data management
          - Machine learning
          - Natural language processing
          - SQL database management
          - Building interactive devices with circuitry and microcontrollers

      - job: "PhD Student/Research Assistant"
        company: "Univ Southern Mississippi"
        companyUrl: "https://www.usm.edu/gulf-coast-research-laboratory/index.php"
        date: "Jan 2016 - Mar 2022"
        featuredLink:
          enable: false
        info:
          enable: false
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          I was a PhD student under the advisement of Dr. Eric Saillant at the Gulf Coast Research Laboratory in Ocean Springs, MS. My committee
          included Dr. Leila Hamdan, Dr. Kenneth Jones, Dr. Frank Hernandez, and the legendary James "Jim" Franks.

          - Assembled 5 tuna genomes (long reads, short reads, hybrid)
          - Created linkage maps from F1 crosses
          - ddRAD-seq
          - Whole-genome evolutionary comparisons
          - Population structure and demography of Blackfin and Yellowfin tunas

      - job: "Masters Student/Research Assistant"
        company: "TAMU-Corpus Christi"
        companyUrl: "https://www.marinegenomicslab.tamucc.edu/"
        date: "Aug 2012 - Dec 2015"
        info:
          enable: false
        featuredLink:
          name: "Publication"
          enable: true
          url: "https://link.springer.com/article/10.1007/s00227-019-3533-1"
        content: |
          I was a Masters student under the advisement of Dr. David Portnoy at Texas A&M Univeristy - Corpus Christi. My committee included Drs. Derek Hogan and
          Jose Guardiola. I was also mentored under the watchful eye of Dr. Stuart Willis.

          - ddRAD-seq
          - Coastal shark longlining
          - Teaching Assistant: Anatomy and Physiology, Biology

      - job: "Fellow"
        company: "Eurasia Foundation"
        companyUrl: "https://www.eurasia.org/project/u-s-russia-social-expertise-exchange/"
        date: "Mar 2014 - May 2014"
        info:
          enable: false
        featuredLink:
          enable: false
        content: |
          I was part of a team consisting of experts from Russia and the United States to review best practices of the maintenance and stewardship of national parks and refuges between the two nations.

      - job: "Intern"
        company: "Dauphin Island Sea Lab"
        companyUrl: "https://www.disl.edu/"
        date: "Aug 2012 - Aug 2014"
        info:
          enable: false
        content: |
          I was an intern in the Carmichael lab (oyster ecology/restoration, manatee ecology, sediment microchemistry)
          and the Powers lab (reef fish, shark, and oyster ecology).

      - job: "GS-05 Wildlife Technician"
        company: "USDA"
        companyUrl: "https://www.aphis.usda.gov/aphis/newsroom/stakeholder-info/sa_by_date/sa-2022/hpai-indiana"
        date: "June 2011 - Dec 2011"
        info:
          enable: false
        content: |
          I was a member of a team stationed at John F. Kennedy International Airport (New York City) to prevent wildlife-aviation conflicts.
          This included monitoring the taxiways and airport perimeter, and wildlife removal.

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Doctor of Philosophy - Coastal Sciences"
        school:
          name: "University of Southern Mississippi"
          url: "https://www.usm.edu/gulf-coast-research-laboratory/index.php"
        date: "2017 - 2022"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |-
          Advisor: Eric Saillant

          - Chapter 1: Genomic resources for the Yellowfin tuna - [link](https://doi.org/10.1007/s11033-023-09117-6)
          - Chapter 2: Population structure and demography of the Yellowfin tuna in the Atlantic Ocean
          - Chapter 3: Population structure and demography of the Blackfin tuna in the Atlantic Ocean - [link](https://doi.org/10.1093/icesjms/fsad012)
          - Chapter 4: Evolutionary history of the Thunnus genus using whole genome comparisons
      - title: "Master of Science - Fisheries and Mariculature"
        school:
          name: "Texas A&M University - Corpus Christi"
          url: "https://www.tamucc.edu"
        date: "2014 - 2016"
        content: |-
          Advisor: David Portnoy

          Project: Population structure and demography of the Blacknose shark in the Atlantic Ocean
        featuredLink:
          enable: true
          name: "Publication"
          url: "https://link.springer.com/article/10.1007/s00227-019-3533-1"
      - title: "Bachelor of Science - Aquatics and Fisheries Science"
        school:
          name: "State University of New York College of Environmental Sciences and Forestry"
          url: "https://www.esf.edu"
        date: "2007 - 2020"
        content: |-
          Advisor: Kimberly Schulz

          Project: Trophic differences in planktonic assemblages between a pristine and invaded lake in the Adirondacks

  # Achievements
  achievements:
    enable: false
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    items:
      - title: PopGen.jl
        content: Population genetic analyses in the Julia language
        image: /images/popgen.png
        featured:
          name: explore
          link: https://biojulia.net/PopGen.jl/
        badges:
          - "Julia"
          - "Analysis"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=PopGenjl
          - icon: fab fa-github
            url: https://github.com/BioJulia/PopGen.jl
      - title: Harpy
        content: Haplotagging data processing pipeline
        image: /images/harpy.png
        featured:
          name: explore
          link: https://pdimens.github.io/HARPY/#/
        badges:
          - "Pipeline"
          - "Analysis"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Harpy
          - icon: fab fa-github
            url: https://github.com/pdimens/harpy
      - title: LepWrap
        content: A Snakemake-based pipeline to run LepMap3 and LepAnchor
        image: /images/lepwrap.png
        featured:
          name: explore
          link: https://github.com/pdimens/lepwrap
        badges:
           - "Pipeline"
           - "Analysis"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=LepWrap
          - icon: fab fa-github
            url: https://github.com/pdimens/lepwrap
      - title: Gust
        content: A Snakemake-based pipeline for whole-genome comparison and phyolgenetic analysis using genome assemblies
        image: /images/gust.png
        featured:
          name: explore
          link: https://www.github.com/pdimens/gust
        badges:
           - "Pipeline"
           - "Analysis"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Gust
          - icon: fab fa-github
            url: https://www.github.com/pdimens/gust
      - title: dDocent
        content: A pipeline for RAD sequencing 
        image: /images/ddocent.png
        featured:
          name: explore
          link: https://www.ddocent.com/
        badges:
           - "Pipeline"
           - "Analysis"
        links:
          - icon: fab fa-github
            url: https://github.com/jpuritz/dDocent

  #Contact
  contact:
    enable: true
    content: I'm pretty responsive to emails. If you would like to get in touch, don't hesistate to write!
    email: pdimens@gmail.com
    btnName: Contact Me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/pdimens
      linkedin: https://www.linkedin.com/in/pavelvdimens
      twitter: https://twitter.com/pvdimens
