name: Deployment

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        #with:
        #  hugo-version: "0.128.1"

      - name: Build
        run: hugo --gc --minify --themesDir themes

      - name: Deploy website to the branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: site
          publish_dir: .
          user_name: hugo-profile bot
          user_email: githubactionsbot@users.noreply.github.com